/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 91f55907f309d94be512cb79946244cb)
interface __BaseEnv_CloudflareEnv {
	RATE_LIMIT_KV: KVNamespace;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	NEXT_PUBLIC_SITE_URL: string;
	GEMINI_API_KEY: string;
	GEMINI_MODEL: string;
	NEXT_PUBLIC_TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	RATE_LIMIT_SECRET: string;
	NEXT_PUBLIC_GA_MEASUREMENT_ID: string;
	WORKER_SELF_REFERENCE: Fetcher /* plotripple-quest */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_SITE_URL" | "GEMINI_API_KEY" | "GEMINI_MODEL" | "NEXT_PUBLIC_TURNSTILE_SITE_KEY" | "TURNSTILE_SECRET_KEY" | "RATE_LIMIT_SECRET" | "NEXT_PUBLIC_GA_MEASUREMENT_ID">> {}
}
