export const CHRONICLE_EXPAND_FOLLOW_UP_COUNT = 2;
export const CHRONICLE_MAX_DEPTH = 3;
export const CHRONICLE_MAX_NODES = 25;
export const CHRONICLE_LIBRARY_MAX_ITEMS = 20;
export const EXPAND_EXISTING_TITLE_MAX = 200;
export const EXPAND_EXISTING_TITLES_MAX = 24;
